extends:
  - plugin:import/errors
settings:
  import/resolver:
    webpack:
      config: 'webpack.config.js'
      config-index: 0
rules:
  node/no-unsupported-features: 0
env:
  node: true # webpack
  browser: true
